<?php

/**
 * @file
 * Installs, updates and uninstalls module variables and settings.
 *
 * Copyright (c) 2011 by Marco Zanon (http://www.marcozanon.com)
 * Released under GPLv2 license
 * Idea and code inspired by http://www.beacon9.ca/labs/drupal-7-private-files-module
 */

/**
 * Implements hook_uninstall().
 */
function private_files_download_permission_uninstall() {
  variable_del('private_files_download_permission_unprotected_subfolder');
}
