<?php

/**
 * @file
 * Handles both module settings and its behaviour.
 *
 * Copyright (c) 2011-2012 by Marco Zanon (http://www.marcozanon.com)
 * Released under GPLv2 license
 * Idea and code inspired by http://www.beacon9.ca/labs/drupal-7-private-files-module
 */

/**
 * Implements hook_permission().
 */
function private_files_download_permission_permission() {
  return array(
    'administer private files download permission' => array(
      'title' => t('Administer Private files download permission'),
      'description' => t('Access module configuration.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function private_files_download_permission_menu() {
  return array(
    'admin/config/media/private-files-download-permission/view' => array(
      'title' => 'Private files download permission',
      'description' => 'Show directory list.',
      'page callback' => 'private_files_download_permission_view',
      'access arguments' => array('administer private files download permission'),
      'type' => MENU_NORMAL_ITEM,
    ),
    'admin/config/media/private-files-download-permission/remove/%' => array(
      'title' => 'Private files download permission',
      'description' => 'Remove directory from list.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('private_files_download_permission_remove', 5),
      'access arguments' => array('administer private files download permission'),
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * Returns the list of all directories under control.
 */
function private_files_download_permission_directory_list() {
  $directory_list = &drupal_static(__FUNCTION__);
  if (!isset($directory_list)) {
    $directory_list = db_query('SELECT   *
                                FROM     {private_files_download_permission_directory}
                                ORDER BY {private_files_download_permission_directory}.path ASC')
                        ->fetchAllAssoc('did');
  }
  return $directory_list;
}

/**
 * (Page callback.) Prepares and displays the main directory list view.
 */
function private_files_download_permission_view() {
  $output = '';
  // Check if the file system download method is set to private.
  if ('private' !== file_default_scheme()) {
    drupal_set_message(t('You need to !set_your_file_system_download_method to private.', array('!set_your_file_system_download_method' => l(t('set your file system download method'), 'admin/config/media/file-system'))), 'error');
  }
  // Display the private file system path.
  $output .= '<p>' . t('Your private file system path is %path.', array('%path' => variable_get('file_private_path'))) . '</p>';
  // Retrieve the directory list and display it as a table.
  $directory_list = private_files_download_permission_directory_list();
  $rows = array();
  foreach ($directory_list as $directory) {
    $rows[] = array(
      $directory->path,
      l(t('Edit'), 'admin/config/media/private-files-download-permission/edit/' . $directory->did),
      l(t('Remove'), 'admin/config/media/private-files-download-permission/remove/' . $directory->did),
    );
  }
  $output .= theme_table(array(
    'header' => array(
      t('Directory path'),
      array(
        'data' => t('Operations'),
        'colspan' => 2,
      ),
    ),
    'rows' => $rows,
    'attributes' => array(),
    'caption' => NULL,
    'colgroups' => array(),
    'sticky' => FALSE,
    'empty' => t('The directory list is empty.'),
  ));
  // Display the 'Add directory' link.
  $output .= '<p>' . l(t('Add directory'), 'admin/config/media/private-files-download-permission/edit') . '</p>';
  // Return output.
  return $output;
}

/**
 * (Form callback.) Displays a confirmation dialog to remove a directory from
 * the directory list.
 */
function private_files_download_permission_remove($form, &$form_state, $did) {
  // Check that $did is actually a valid directory id.
  $directory_list = private_files_download_permission_directory_list();
  if (!in_array($did, array_keys($directory_list))) {
    drupal_set_message(t('You need to pass a valid directory id.'), 'error');
    return;
  }
  // Prepare the value to be eventually submitted.
  $form['did'] = array(
    '#type'  => 'value',
    '#value' => $did,
  );
  // Return the confirmation form.
  return confirm_form(
    $form,
    t('Are you sure you want to remove @path from the directory list?', array('@path' => $directory_list[$did]->path)),
    'admin/config/media/private-files-download-permission/view',
    t('This action cannot be undone.'),
    t('Remove directory from list'),
    t('Cancel')
  );
}

/**
 * (Page callback.) Configures a directory.
 */
function private_files_download_permission_settings($form, &$form_state) {
  if ('public' == file_default_scheme()) {
    drupal_set_message(t('You need to enable the private file system before you setup this module.'), 'error');
  }
  $form['private_files_download_permission_unprotected_subfolder'] = array(
    '#type' => 'textfield',
    '#title' => t('Unprotected subfolder'),
    '#default_value' => variable_get('private_files_download_permission_unprotected_subfolder'),
    '#size' => '60',
    '#description' => t('Use a relative path and don\'t add leading or trailing slashes. Caution: private downloads filters will be bypassed for the above subfolder (making it "public")!'),
  );
  return system_settings_form($form);
}

/**
 * (Form callback.) Validates the directory configuration form.
 */
function private_files_download_permission_settings_validate($form, &$form_state) {
  // Make sure the unprotected subfolder variable does not use leading or trailing slashes.
  $unprotected_subfolder = $form_state['values']['private_files_download_permission_unprotected_subfolder'];
  if (0 < drupal_strlen($unprotected_subfolder)) {
    $first_char = drupal_substr($unprotected_subfolder, 0, 1);
    $last_char = drupal_substr($unprotected_subfolder, -1, 1);
    if (('/' == $first_char) || ('\\' == $first_char)) {
      form_set_error('private_files_download_permission_unprotected_subfolder', t('You cannot use leading slashes.'));
    }
    if (('/' == $last_char) || ('\\' == $last_char)) {
      form_set_error('private_files_download_permission_unprotected_subfolder', t('You cannot use trailing slashes.'));
    }
  }
}

/**
 * Implements hook_file_download().
 */
function private_files_download_permission_file_download($uri) {
  $path = explode('/', $uri);
  if (($path[2] === variable_get('private_files_download_permission_unprotected_subfolder')) || (user_access('download private files'))) {
    return array('Content-Type' => file_get_mimetype($uri));
  }
  return -1;
}
