<?php

/**
 * @file
 * Installs, updates and uninstalls module variables and settings.
 *
 */

/**
 * Implements hook_schema().
 */
function private_files_download_permission_schema() {
  return array(
    'private_files_download_permission_directory_user' => array(
      'description'  => 'Users having per-directory download permission.',
      'fields'       => array(
        'duid' => array('type' => 'serial', 'unsigned' => TRUE, 'not null' => TRUE),
        'did'  => array('type' => 'int', 'unsigned' => TRUE, 'not null' => TRUE),
        'uid'  => array('type' => 'int', 'unsigned' => TRUE, 'not null' => TRUE),
      ),
      'primary key'  => array('duid'),
      'foreign keys' => array(
        'private_files_download_permission_directory_user' => array(
          'table'   => 'users',
          'columns' => array('uid' => 'uid'),
        ),
      ),
      'unique keys'  => array(),
      'indexes'      => array(),
    ),
  );
}

/**
 * Implements hook_enable().
 */
function private_files_download_permission_enable() {
  // Purge directory list from cache.
  backdrop_static_reset('private_files_download_permission_directory_list');
}

/**
 * Implements hook_uninstall().
 */
function private_files_download_permission_uninstall() {
  $transaction = db_transaction();
  try {
    db_query('ALTER TABLE {private_files_download_permission_directory_user}
      DROP FOREIGN KEY {private_files_download_permission_directory_user}');
  }
  catch (Exception $e) {
    $transaction->rollback();
    $t = get_t();
    backdrop_set_message($t('An error occurred while removing the module. Please check the log for details.'), 'error');
  }

  // Purge directory list from cache.
  backdrop_static_reset('private_files_download_permission_directory_list');
}

/**
 * Implements hook_update_last_removed().
 */
function private_files_download_permission_update_last_removed() {
  return 7204;
}

/**
 * @defgroup updates-7.x-to-1.x Updates from 7.x to 1.x
 * @{
 * Update functions from Drupal 7.x to Backdrop CMS 1.x.
 */

/**
 * Move private_files_download_permission settings from variables to config.
 */

function private_files_download_permission_update_1000() {
  // Migrate variables to config.
  $config = config('private_files_download_permission.settings');
  $config->set('attachment_mode', update_variable_get('private_files_download_permission_attachment_mode', FALSE));
  $config->set('by_user_checks', update_variable_get('private_files_download_permission_by_user_checks', FALSE));
  $config->set('cache_users', update_variable_get('private_files_download_permission_cache_users', FALSE));
  $config->set('debug_mode', update_variable_get('private_files_download_permission_debug_mode', FALSE));

  $config->save();

  // Delete variables.
  update_variable_del('private_files_download_permission_attachment_mode');
  update_variable_del('private_files_download_permission_by_user_checks');
  update_variable_del('private_files_download_permission_cache_users');
  update_variable_del('private_files_download_permission_debug_mode');

}

/**
 * Move some private_files_download_permission configuration from table to config files.
 */
function private_files_download_permission_update_1001() {
  db_query('SET FOREIGN_KEY_CHECKS=0');
  if (db_table_exists('private_files_download_permission_directory')) {
    $directories = db_select('private_files_download_permission_directory', 'd')
    ->fields('d')
    ->execute()
    ->fetchAllAssoc('did');

    foreach($directories as $directory) {
      $config = config('private_files_download_permission.settings');
      $config->set('directories.' . $directory->did, array(
        'path' => $directory->path,
        'bypass' => $directory->bypass,
        'grant_file_owners' => $directory->grant_file_owners,
      ));
      $config->save();
    }
    db_drop_table('private_files_download_permission_directory');
  }

  if (db_table_exists('private_files_download_permission_directory_role')) {
    $directory_roles = db_select('private_files_download_permission_directory_role', 'dr')
    ->fields('dr')
    ->execute()
    ->fetchAllAssoc('drid');

    foreach($directory_roles as $role) {
      $config = config('private_files_download_permission.settings');
      if ($role->rid == 1) {
        $role->rid = 'anonymous';
      } elseif ($role->rid == 2) {
        $role->rid = 'authenticated';
      }
      $roles[$role->did][] = $role->rid;
    }
    $config->set('directories.' . $role->did . '.roles', $roles);
    $config->save();
    db_drop_table('private_files_download_permission_directory_role');
  }
  db_query('SET FOREIGN_KEY_CHECKS=1');
}

/**
 * Remove foreign keys on the private_files_download_permission_directory_user table.
 */
function private_files_download_permission_update_1002() {
  if (!db_table_exists('private_files_download_permission_directory_user')) {
    return;
  }
  db_query('ALTER TABLE {private_files_download_permission_directory_user}
    DROP FOREIGN KEY {private_files_download_permission_directory_2}');
  db_query('ALTER TABLE {private_files_download_permission_directory_user}
    DROP FOREIGN KEY {private_files_download_permission_directory_user}');
}

/*
 * @} End of "defgroup updates-7.x-to-1.x"
 * The next series of updates should start at 2000.
 */
